### ISSUE TITLE
Exception when render Dexterity Folder object on Plone 4.3.7

### ISSUE THREAD

**Issue by rudaporto** [plone/plone.rest#14]
I created a fresh Plone site and installed:

```
plone.dexterity==2.3.5
plone.app.contenttypes==1.1b6
plone.rest==1.0.2a
plone.restapi==0.1
wildcard.media==1.2b5
```
After that I can do REST requests on SiteRoot and Dexterity Video type provided by wildcard.media:

```python
In [33]: headers = dict(Accept='application/json')
In [34]: response = requests.get('http://159.182.80.108/educadom/', headers=headers)
In [35]: response.json()
Out[35]: 
{u'@context': u'http://www.w3.org/ns/hydra/context.jsonld',
 u'@id': u'http://159.182.80.108/educadom',
 u'@type': u'SiteRoot',
 u'member': [{u'@id': u'http://159.182.80.108/educadom/front-page',
   u'description': u'',
   u'title': u'Bem-vindo ao Plone'},
  {u'@id': u'http://159.182.80.108/educadom/news',
   u'description': u'',
   u'title': u'Not\xedcias'},
  {u'@id': u'http://159.182.80.108/educadom/events',
   u'description': u'',
   u'title': u'Eventos'},
  {u'@id': u'http://159.182.80.108/educadom/Members',
   u'description': u'',
   u'title': u'Usu\xe1rios'},
  {u'@id': u'http://159.182.80.108/educadom/videos',
   u'description': u'',
   u'title': u'Videos'},
  {u'@id': u'http://159.182.80.108/educadom/galeria',
   u'description': u'',
   u'title': u'Galeria'}],
 u'parent': {}}

In [36]: response = requests.get('http://159.182.80.108/educadom/videos/pedro-barros', headers=headers)
In [37]: response.json()
Out[37]: 
{u'@context': u'http://www.w3.org/ns/hydra/context.jsonld',
 u'@id': u'http://159.182.80.108/educadom/videos/pedro-barros',
 u'@type': u'WildcardVideo',
 u'contributors': [],
 u'creators': [u'admin'],
 u'description': u'',
 u'effective': u'2015-10-27T21:13:23-02:00',
 u'expires': u'2499-12-31T00:00:00-02:00',
 u'height': u'320',
 u'icon': u'++resource++plone.dexterity.item.gif',
 u'isPrincipiaFolderish': u'0',
 u'language': u'pt-br',
 u'meta_type': u'Dexterity Item',
 u'parent': {u'@id': u'http://159.182.80.108/educadom/videos',
  u'description': u'',
  u'title': u'Videos'},
 u'title': u'Pedro Barros',
 u'video_file': u'http://159.182.80.108/educadom/videos/pedro-barros/Pedro Barros - RTMF Bowl Session in Florianopolis, Brazil.mp4',
 u'width': u'640'}
```
I install plone.app.contentypes and add a new Dexteriry Folder at:
http://159.182.80.108/educadom/teste

When I try to render webview I got this exception:

```python
2015-10-27T21:47:44 ERROR Zope.SiteErrorLog 1445989664.870.10711077184 http://159.182.80.108/educadom/teste
Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.BaseRequest, line 444, in traverse
  Module plone.rest.patches, line 55, in DexterityContent__before_publishing_traverse__
AttributeError: 'super' object has no attribute '__before_publishing_traverse__'
```

It's a bug on plone.rest or something missing on plone.dexterity?

Also, ATContentTypes do not respond to REST requests?

```python
In [41]: response = requests.get('http://159.182.80.108/educadom/galeria', headers=headers)
In [42]: response.status_code
Out[42]: 500

In [43]: response.text
Out[43]: u'<html>\n<head>\n<base href="http://159.182.80.108/educadom/galeria/" />\n<title>Site Error</title></head>\n<body bgcolor="#FFFFFF">\n\n\n  <h2>Site Error</h2>\n\n  <p>An error was encountered while publishing this resource.\n  </p>\n  \n  <p>\n      <strong>Error Type: AttributeError</strong><br/>\n      <strong>Error Value: main_template</strong><br/> \n  </p>\n \n  <hr noshade="noshade" />\n \n  <p>Troubleshooting Suggestions</p>\n\n  <ul>\n            <li>The URL may be incorrect.</li>\n      <li>The parameters passed to this resource may be incorrect.</li>\n      <li>A resource that this resource relies on may be encountering\n          an error.</li>\n  </ul>\n\n  <p>For more detailed information about the error, please\n  refer to the error log.\n  </p>\n\n  <p>If the error persists please contact the site maintainer.\n  Thank you for your patience.\n  </p>\n\n  \n\n</body>\n</html>\n'
```

**Comment by rudaporto** [comment]
I also tried plone.rest 1.0a1 but my zope instance do not start, follow failure:

```python
./bin/client1 fg
2015-10-27 22:29:18 INFO ZServer HTTP server started at Tue Oct 27 22:29:18 2015
	Hostname: 0.0.0.0
	Port: 8081
2015-10-27 22:29:18 INFO Zope Set effective user to "plone_daemon"
2015-10-27 22:29:21 INFO ZEO.ClientStorage zeostorage ClientStorage (pid=4486) created RW/normal for storage: '1'
2015-10-27 22:29:21 INFO ZEO.cache created temporary cache file '<fdopen>'
2015-10-27 22:29:21 INFO ZEO.ClientStorage zeostorage Testing connection <ManagedClientConnection ('127.0.0.1', 8100)>
2015-10-27 22:29:21 INFO ZEO.zrpc.Connection(C) (127.0.0.1:8100) received handshake 'Z3101'
2015-10-27 22:29:21 INFO ZEO.ClientStorage zeostorage Server authentication protocol None
2015-10-27 22:29:21 INFO ZEO.ClientStorage zeostorage Connected to storage: ('localhost.localdomain', 8100)
2015-10-27 22:29:21 INFO ZEO.ClientStorage zeostorage No verification necessary -- empty cache
2015-10-27 22:29:26 WARNING plone.behavior Specifying 'for' in behavior 'Related items' if no 'factory' is given has no effect and is superfluous.
2015-10-27 22:29:26 WARNING wildcard.media ffmpeg not installed. wildcard.video will not function
2015-10-27 22:29:26 WARNING wildcard.media avprobe not installed. wildcard.video will not function
2015-10-27 22:29:28 INFO plone.validatehook Wrapped the Zope2 zpublisher validation hook
2015-10-27 22:29:28 INFO ZEO.ClientStorage zeostorage Disconnected from storage: "('localhost.localdomain', 8100)"
Traceback (most recent call last):
  File "/data/plone4/zeocluster/parts/client1/bin/interpreter", line 332, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/data/plone4/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/data/plone4/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/data/plone4/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/__init__.py", line 86, in prepare
    self.startZope()
  File "/data/plone4/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/Startup/__init__.py", line 262, in startZope
    Zope2.startup()
  File "/data/plone4/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/data/plone4/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/App/startup.py", line 118, in startup
    load_zcml()
  File "/data/plone4/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/data/plone4/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 649, in file
    include(context, name, package)
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/data/plone4/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/data/plone4/Python-2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/data/plone4/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/data/plone4/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/data/plone4/buildout-cache/eggs/Zope2-2.13.23-py2.7.egg/OFS/metaconfigure.py", line 46, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/data/plone4/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/data/plone4/Python-2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/data/plone4/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/data/plone4/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/data/plone4/buildout-cache/eggs/z3c.autoinclude-0.3.5-py2.7.egg/z3c/autoinclude/zcml.py", line 104, in includePluginsDirective
    includeZCMLGroup(_context, info, filename)
  File "/data/plone4/buildout-cache/eggs/z3c.autoinclude-0.3.5-py2.7.egg/z3c/autoinclude/zcml.py", line 30, in includeZCMLGroup
    include(_context, filename, includable_package)
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/data/plone4/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/data/plone4/Python-2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/data/plone4/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/data/plone4/Python-2.7/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 541, in include
    f = openInOrPlain(path)
  File "/data/plone4/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 429, in openInOrPlain
    fp = open(filename)
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/data/plone4/zeocluster/parts/client1/etc/site.zcml", line 16.2-16.23
    ZopeXMLConfigurationError: File "/data/plone4/buildout-cache/eggs/Products.CMFPlone-4.3.7-py2.7.egg/Products/CMFPlone/configure.zcml", line 98.4-102.10
    ZopeXMLConfigurationError: File "/data/plone4/zeocluster/src/plone.restapi/src/plone/restapi/configure.zcml", line 18.2-18.56
    IOError: [Errno 2] No such file or directory: '/data/plone4/buildout-cache/eggs/plone.rest-1.0a1-py2.7.egg/plone/rest/configure.zcml'
[root@bz1utgpssweb01 zeocluster]# ls /data/plone4/buildout-cache/eggs/plone.rest-1.0a1-py2.7.egg/plone/rest/configure.zcml
ls: impossível acessar /data/plone4/buildout-cache/eggs/plone.rest-1.0a1-py2.7.egg/plone/rest/configure.zcml: Arquivo ou diretório não encontrado
```

**Comment by tisto** [comment]
@rudaporto could you give it another try with the latest version and report back?

**Comment by tisto** [comment]
No activity. Will close the issue. @rudaporto feel free to re-open if the bug still persists with the latest version.
