### ISSUE TITLE
plone.rest 4.0.0 release

### ISSUE THREAD

**Issue by tisto** [plone/plone.rest#159]
@mauritsvanrees I am trying to do a 4.0.0 release for plone.rest but I get this error trace both in buildout.coredev (6.1) and in the plone.rest repo:

````
Upload to pypi (Y/n)? y
Uploading distributions to https://upload.pypi.org/legacy/
Uploading plone.rest-4.0.0-py2.py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.6/132.6 kB • 00:00 • 52.1 MB/s
Uploading plone.rest-4.0.0.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.5/130.5 kB • 00:00 • 55.1 MB/s

View at:
https://pypi.org/project/plone.rest/4.0.0/
Ok to update coredev versions.cfg/checkouts.cfg? (Y/n)? y
Updating buildout versions
Traceback (most recent call last):
  File "/Users/timo/workspace/plone/buildout.coredev-6.1/src/plone.rest/../../bin/fullrelease", line 64, in <module>
    sys.exit(zest.releaser.fullrelease.main())
  File "/Users/timo/workspace/plone/buildout.coredev-6.1/eggs/zest.releaser-9.0.0b1-py3.9.egg/zest/releaser/fullrelease.py", line 27, in main
    releaser.run()
  File "/Users/timo/workspace/plone/buildout.coredev-6.1/eggs/zest.releaser-9.0.0b1-py3.9.egg/zest/releaser/baserelease.py", line 430, in run
    self._run_hooks("after")
  File "/Users/timo/workspace/plone/buildout.coredev-6.1/eggs/zest.releaser-9.0.0b1-py3.9.egg/zest/releaser/baserelease.py", line 423, in _run_hooks
    utils.run_hooks(self.zest_releaser_config, which_releaser, when, self.data)
  File "/Users/timo/workspace/plone/buildout.coredev-6.1/eggs/zest.releaser-9.0.0b1-py3.9.egg/zest/releaser/utils.py", line 594, in run_hooks
    run_entry_points(which_releaser, when, data)
  File "/Users/timo/workspace/plone/buildout.coredev-6.1/eggs/zest.releaser-9.0.0b1-py3.9.egg/zest/releaser/utils.py", line 610, in run_entry_points
    plugin(data)
  File "/Users/timo/workspace/plone/buildout.coredev-6.1/src/plone.releaser/plone/releaser/release.py", line 214, in update_core
    update_versions(package_name, new_version)
  File "/Users/timo/workspace/plone/buildout.coredev-6.1/src/plone.releaser/plone/releaser/release.py", line 296, in update_versions
    for filename in glob.glob("versions*.cfg", root_dir=coredev_dir):
TypeError: glob() got an unexpected keyword argument 'root_dir'
````

Any clue what causes this? I tried to switch from Py 3.8 to 3.9 but that did not solve the problem.

**Comment by davisagli** [comment]
@tisto According to the Python docs, the root_dir parameter was added in Python 3.10

**Comment by davisagli** [comment]
@mauritsvanrees plone.releaser claims to support Python 3.8+, so this might be a bug there. The code which uses `root_dir` was added in https://github.com/plone/plone.releaser/pull/54

**Comment by tisto** [comment]
@davisagli thx! Python 3.10 works. plone.rest 4.0.0 released:

https://pypi.org/project/plone.rest/4.0.0/

**Comment by mauritsvanrees** [comment]
Ah, I am only using it on Python 3.11.
